/***************************

  Populate the downloads table

****************************/

insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (1, 'Quadro RTX 5000', 'NVIDIA', 'bhallor1', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (2, 'GeForce MX350', 'NVIDIA', 'emacaindreish', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (3, 'GeForce RTX 3080 Ti Mobile', 'NVIDIA', 'bdradey8', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (4, 'GeForce GTX 1060 6 GB GP104', 'NVIDIA', 'mdrinnan15', 31);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (5, 'A100 PCIe 80 GB', 'NVIDIA', 'trumboldq', 27);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (6, 'GeForce GT 1030 DDR4', 'NVIDIA', 'ttomane', 18);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (7, 'GeForce GTX 1660 Ti Max-Q', 'NVIDIA', 'wgrebert2c', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (8, 'A16 PCIe', 'NVIDIA', 'dpiddletownf', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (9, 'T600 Mobile', 'NVIDIA', 'emacaindreish', 40);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (10, 'Quadro RTX 3000 Mobile', 'NVIDIA', 'afookes1n', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (11, 'GeForce MX230', 'NVIDIA', 'adanielyf', 7);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (12, 'GRID RTX T10-16', 'NVIDIA', 'mludlama', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (13, 'GRID RTX T10-16', 'NVIDIA', 'cnesey2', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (14, 'GeForce RTX 2060 Mobile', 'NVIDIA', 'mduforek', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (15, 'GeForce RTX 2060 Max-Q Refresh', 'NVIDIA', 'gferry22', 18);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (16, 'GeForce GTX 1070 GDDR5X', 'NVIDIA', 'bhallor1', 46);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (17, 'Tesla T4', 'NVIDIA', 'farmes3', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (18, 'Tesla V100 SXM3 32 GB', 'NVIDIA', 'fkeepin1f', 47);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (19, 'A100 PCIe', 'NVIDIA', 'kberkowitz2o', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (20, 'GeForce RTX 3080 12 GB', 'NVIDIA', 'dmillomm', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (21, 'Tesla PG503-216', 'NVIDIA', 'npalleske1q', 36);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (22, 'GeForce RTX 4090', 'NVIDIA', 'blarmour2b', 35);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (23, 'GRID A100A', 'NVIDIA', 'bhallor1', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (24, 'GeForce GTX 1060 6 GB Rev. 2', 'NVIDIA', 'rcastelluzzi1f', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (25, 'Quadro RTX 4000 Mobile', 'NVIDIA', 'ymcphail1c', 35);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (26, 'CMP 70HX', 'NVIDIA', 'gcasemore1x', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (27, 'A10 PCIe', 'NVIDIA', 'kberkowitz2o', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (28, 'GeForce GT 1010', 'NVIDIA', 'doshieldsj', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (29, 'GeForce RTX 3080', 'NVIDIA', 'fspellecy6', 46);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (30, 'GeForce GTX 1650 Mobile', 'NVIDIA', 'dharbour1m', 0);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (31, 'GeForce GTX 1050 Max-Q', 'NVIDIA', 'bdradey8', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (32, 'Quadro P2000 Mobile', 'NVIDIA', 'ymcphail1c', 2);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (33, 'GeForce RTX 2080 SUPER Mobile', 'NVIDIA', 'dliles1e', 13);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (34, 'GeForce RTX 3070 Ti Mobile', 'NVIDIA', 'zstobie15', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (35, 'GeForce RTX 2080 SUPER Mobile', 'NVIDIA', 'twyrill7', 1);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (36, 'GeForce RTX 3050 Ti Mobile', 'NVIDIA', 'wflattg', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (37, 'A100 PCIe 80 GB', 'NVIDIA', 'rsimcoe1u', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (38, 'GeForce RTX 2080 SUPER', 'NVIDIA', 'lwhittlesn', 46);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (39, 'GeForce GT 1010 DDR4', 'NVIDIA', 'wstaterfield17', 2);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (40, 'Tesla V100 FHHL', 'NVIDIA', 'mludlama', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (41, 'GeForce RTX 2080 Max-Q', 'NVIDIA', 'dmillomm', 37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (42, 'GeForce RTX 3050 8 GB', 'NVIDIA', 'ddarey1c', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (43, 'GeForce MX330', 'NVIDIA', 'icosgreave1b', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (44, 'PG506-232', 'NVIDIA', 'lwhittlesn', 22);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (45, 'Tesla V100 DGXS 16 GB', 'NVIDIA', 'gnotleyc', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (46, 'TITAN RTX', 'NVIDIA', 'bluipoldi', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (47, 'GeForce RTX 2070 Max-Q', 'NVIDIA', 'kpopworth2r', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (48, 'GeForce RTX 2070 SUPER Max-Q', 'NVIDIA', 'ugrishakov2p', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (49, 'TITAN RTX', 'NVIDIA', 'rfishleigh1u', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (50, 'Quadro T1000 Mobile GDDR6', 'NVIDIA', 'ajovis1p', 49);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (51, 'RTX A500 Embedded', 'NVIDIA', 'aavramovitz9', 44);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (52, 'Tesla V100 DGXS 16 GB', 'NVIDIA', 'ajovis1p', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (53, 'Quadro RTX 3000 Mobile Refresh', 'NVIDIA', 'espooner5', 44);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (54, 'GeForce MX350', 'NVIDIA', 'trumboldq', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (55, 'A2', 'NVIDIA', 'ecafferty12', 40);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (56, 'GeForce GTX 1650 GDDR6', 'NVIDIA', 'oheaslya', 8);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (57, 'Quadro P3200 Mobile', 'NVIDIA', 'rcastelluzzi1f', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (58, 'Quadro T1000 Max-Q', 'NVIDIA', 'icosgreave1b', 8);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (59, 'GeForce RTX 3050 Ti Mobile', 'NVIDIA', 'wstaterfield17', 23);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (60, 'P104-101', 'NVIDIA', 'bdradey8', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (61, 'GeForce MX330', 'NVIDIA', 'omacfayden2f', 2);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (62, 'Quadro P4200 Mobile', 'NVIDIA', 'lwhittlesn', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (63, 'GeForce RTX 2070 Mobile Refresh', 'NVIDIA', 'mfuke23', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (64, 'GeForce RTX 2060', 'NVIDIA', 'rscholesm', 8);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (65, 'GeForce GTX 1060 6 GB GDDR5X', 'NVIDIA', 'doshieldsj', 5);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (66, 'GeForce MX230', 'NVIDIA', 'doshieldsj', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (67, 'GeForce RTX 2070 SUPER Max-Q', 'NVIDIA', 'dpiddletownf', 14);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (68, 'T1000', 'NVIDIA', 'zstobie15', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (69, 'Quadro T1200 Mobile', 'NVIDIA', 'lgredden9', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (70, 'GeForce GTX 1060 8 GB GDDR5X', 'NVIDIA', 'trumboldq', 43);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (71, 'GeForce GTX 1650 Max-Q', 'NVIDIA', 'mludlama', 1);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (72, 'Tesla PG503-216', 'NVIDIA', 'ttomane', 22);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (73, 'GeForce RTX 3060 GA104', 'NVIDIA', 'zjozwik2l', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (74, 'RTX A500 Embedded', 'NVIDIA', 'mduforek', 0);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (75, 'GeForce RTX 3050 Ti Mobile', 'NVIDIA', 'mduforek', 7);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (76, 'RTX A4000', 'NVIDIA', 'afookes1n', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (77, 'CMP 90HX', 'NVIDIA', 'mdomotor23', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (78, 'GeForce RTX 2070 SUPER', 'NVIDIA', 'zstobie15', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (79, 'Quadro RTX 4000 Max-Q', 'NVIDIA', 'tranfieldl', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (80, 'RTX A2000 Embedded', 'NVIDIA', 'emacaindreish', 49);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (81, 'Tesla V100 DGXS 32 GB', 'NVIDIA', 'bbeggn', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (82, 'GeForce GT 1030 GK107', 'NVIDIA', 'jcolgan11', 42);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (83, 'RTX A3000 Mobile', 'NVIDIA', 'obiskupiak1r', 33);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (84, 'GeForce MX250', 'NVIDIA', 'mfuke23', 12);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (85, 'GeForce RTX 3050 8 GB', 'NVIDIA', 'gcasemore1x', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (86, 'GRID RTX T10-16', 'NVIDIA', 'rscholesm', 48);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (87, 'P104-101', 'NVIDIA', 'fwinston2j', 2);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (88, 'GeForce GTX 1050 Ti Max-Q', 'NVIDIA', 'mfuke23', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (89, 'RTX A4500', 'NVIDIA', 'jduffyn5', 36);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (90, 'Quadro RTX 6000 Passive', 'NVIDIA', 'sreignard27', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (91, 'Quadro P2000 Mobile', 'NVIDIA', 'wconfordb', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (92, 'Switch GPU 16nm', 'NVIDIA', 'trumboldq', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (93, 'RTX A6000', 'NVIDIA', 'ctomeoi', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (94, 'Quadro GV100', 'NVIDIA', 'bluipoldi', 5);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (95, 'GeForce MX150 GP107', 'NVIDIA', 'ebrigham8', 7);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (96, 'GeForce RTX 3070', 'NVIDIA', 'fspellecy6', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (97, 'GeForce GTX 1650 Mobile', 'NVIDIA', 'jduffyn5', 15);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (98, 'GeForce GTX 1660 SUPER', 'NVIDIA', 'hellacottz', 16);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (99, 'Tesla V100 DGXS 16 GB', 'NVIDIA', 'wconfordb', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (100, 'GeForce RTX 2070 SUPER Max-Q', 'NVIDIA', 'dtestin26', 16);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (101, 'Quadro RTX 4000 Max-Q', 'NVIDIA', 'oheaslya', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (102, 'GeForce RTX 3080 Ti Max-Q', 'NVIDIA', 'icosgreave1b', 11);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (103, 'Quadro RTX 3000 Mobile Refresh', 'NVIDIA', 'jainscough25', 10);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (104, 'GeForce RTX 4060', 'NVIDIA', 'espooner5', 44);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (105, 'RTX A4 Mobile', 'NVIDIA', 'bheyburn2r', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (106, 'GeForce GTX 1650 Max-Q', 'NVIDIA', 'rcastelluzzi1f', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (107, 'GeForce GT 1030 DDR4', 'NVIDIA', 'afortounj', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (108, 'GeForce GTX 1650 GDDR6', 'NVIDIA', 'npeggram2m', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (109, 'Quadro T1000 Mobile', 'NVIDIA', 'trumboldq', 8);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (110, 'RTX A4500 Embedded', 'NVIDIA', 'fgouldbourn2q', 47);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (111, 'GeForce MX150 GP107', 'NVIDIA', 'smatyja1b', 32);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (112, 'GeForce RTX 2070', 'NVIDIA', 'afortounj', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (113, 'GeForce MX250', 'NVIDIA', 'rsimcoe1u', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (114, 'GeForce GTX 1650 Mobile', 'NVIDIA', 'mduforek', 35);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (115, 'GRID A100A', 'NVIDIA', 'qoliddyc', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (116, 'GeForce RTX 3060 Max-Q', 'NVIDIA', 'gcasemore1x', 37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (117, 'A100 SXM4 40 GB', 'NVIDIA', 'zstobie15', 48);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (118, 'GeForce RTX 2070 SUPER Max-Q', 'NVIDIA', 'aleist8', 2);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (119, 'CMP 30HX', 'NVIDIA', 'ymcphail1c', 2);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (120, 'GeForce GT 1030 GK107', 'NVIDIA', 'gocurrine2h', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (121, 'GeForce RTX 2080 Mobile', 'NVIDIA', 'rscholesm', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (122, 'T1000 8 GB', 'NVIDIA', 'emilligan3', 48);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (123, 'Quadro RTX 8000', 'NVIDIA', 'moreilly0', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (124, 'GeForce GTX 1050 Max-Q', 'NVIDIA', 'gnotleyc', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (125, 'GeForce RTX 4080', 'NVIDIA', 'jduffyn5', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (126, 'CMP 90HX', 'NVIDIA', 'jtruelocke', 5);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (127, 'Quadro RTX 3000 Mobile Refresh', 'NVIDIA', 'wmouat1d', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (128, 'CMP 170HX', 'NVIDIA', 'gbytheway6', 33);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (129, 'GeForce GTX 1650 Ti Max-Q', 'NVIDIA', 'gocurrine2h', 31);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (130, 'Quadro GV100', 'NVIDIA', 'jcolgan11', 40);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (131, 'A16 PCIe', 'NVIDIA', 'pnovik1y', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (132, 'Tesla V100 PCIe 32 GB', 'NVIDIA', 'snyssenk', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (133, 'RTX A3000 Mobile', 'NVIDIA', 'gcasemore1x', 16);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (134, 'GeForce GTX 1650 Mobile', 'NVIDIA', 'fspellecy6', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (135, 'GeForce GTX 1660', 'NVIDIA', 'amoffett24', 43);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (136, 'A16 PCIe', 'NVIDIA', 'cespinosad', 1);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (137, 'GeForce GTX 1660 SUPER', 'NVIDIA', 'ajovis1p', 42);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (138, 'GeForce MX450 25W', 'NVIDIA', 'etripeang', 16);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (139, 'RTX A2000', 'NVIDIA', 'afookes1n', 31);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (140, 'GRID RTX T10-2', 'NVIDIA', 'zstobie15', 1);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (141, 'A100 PCIe 80 GB', 'NVIDIA', 'tshelmardine2q', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (142, 'RTX A4500 Mobile', 'NVIDIA', 'ymcphail1c', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (143, 'P102-101', 'NVIDIA', 'bcater1k', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (144, 'GeForce GTX 1650 GDDR6', 'NVIDIA', 'cespinosad', 7);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (145, 'GeForce RTX 2070 Mobile Refresh', 'NVIDIA', 'bfilgate4', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (146, 'Tesla V100 DGXS 16 GB', 'NVIDIA', 'kberkowitz2o', 2);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (147, 'RTX A4000 Mobile', 'NVIDIA', 'qoliddyc', 0);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (148, 'T400', 'NVIDIA', 'cespinosad', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (149, 'A16 PCIe', 'NVIDIA', 'cnesey2', 0);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (150, 'Quadro T1000 Mobile GDDR6', 'NVIDIA', 'wgrebert2c', 33);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (151, 'CMP 30HX', 'NVIDIA', 'ymcphail1c', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (152, 'GeForce RTX 3050 8 GB GA107', 'NVIDIA', 'mdrinnan15', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (153, 'CMP 170HX', 'NVIDIA', 'rfishleigh1u', 1);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (154, 'GeForce GT 1030 DDR4', 'NVIDIA', 'adanielyf', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (155, 'Tesla PG503-216', 'NVIDIA', 'dliles1e', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (156, 'GeForce RTX 3050 Mobile', 'NVIDIA', 'qoliddyc', 42);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (157, 'Quadro RTX 5000 Max-Q', 'NVIDIA', 'mfuke23', 5);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (158, 'GRID A100A', 'NVIDIA', 'ajovis1p', 3);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (159, 'Tesla PG503-216', 'NVIDIA', 'gnotleyc', 27);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (160, 'GeForce RTX 2060 Mobile Refresh', 'NVIDIA', 'tshelmardine2q', 22);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (161, 'RTX A2000 12 GB', 'NVIDIA', 'mdrinnan15', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (162, 'GeForce RTX 2070 SUPER', 'NVIDIA', 'rgorey1e', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (163, 'GeForce RTX 2070 Mobile', 'NVIDIA', 'ymcphail1c', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (164, 'T600 Mobile', 'NVIDIA', 'ebrigham8', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (165, 'Quadro P520 Mobile', 'NVIDIA', 'afookes1n', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (166, 'Quadro RTX 3000 Mobile', 'NVIDIA', 'dmillomm', 46);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (167, 'RTX A500 Embedded', 'NVIDIA', 'ajovis1p', 27);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (168, 'GeForce RTX 2070 Max-Q', 'NVIDIA', 'dpiddletownf', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (169, 'Quadro T1000 Mobile GDDR6', 'NVIDIA', 'gbytheway6', 32);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (170, 'P102-100', 'NVIDIA', 'tranfieldl', 10);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (171, 'GeForce GTX 1660 Ti Mobile', 'NVIDIA', 'gcasemore1x', 18);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (172, 'GeForce RTX 3080 12 GB', 'NVIDIA', 'wstaterfield17', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (173, 'GeForce MX250', 'NVIDIA', 'ecafferty12', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (174, 'GeForce RTX 2060 Max-Q Refresh', 'NVIDIA', 'icosgreave1b', 5);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (175, 'Tesla PG500-216', 'NVIDIA', 'zjozwik2l', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (176, 'GeForce GTX 1050 3 GB', 'NVIDIA', 'rgowrichx', 11);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (177, 'A30 PCIe', 'NVIDIA', 'espooner5', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (178, 'RTX A4000', 'NVIDIA', 'rscholesm', 11);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (179, 'Quadro P500 Mobile', 'NVIDIA', 'mduforek', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (180, 'GRID A100B', 'NVIDIA', 'lestabrook1w', 36);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (181, 'GeForce RTX 3050 8 GB', 'NVIDIA', 'celnaugh1z', 37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (182, 'Switch GPU 16nm', 'NVIDIA', 'oheaslya', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (183, 'GeForce GTX 1050 Mobile 3 GB', 'NVIDIA', 'smatyja1b', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (184, 'RTX A2000 Mobile', 'NVIDIA', 'aboleyn1j', 49);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (185, 'RTX A500 Embedded', 'NVIDIA', 'kberkowitz2o', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (186, 'Tesla V100 DGXS 32 GB', 'NVIDIA', 'dharbour1m', 15);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (187, 'GeForce GTX 1650 GDDR6', 'NVIDIA', 'etripeang', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (188, 'PG506-232', 'NVIDIA', 'omiskinz', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (189, 'GeForce RTX 2060 12 GB', 'NVIDIA', 'dmillomm', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (190, 'CMP 90HX', 'NVIDIA', 'ecafferty12', 27);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (191, 'GeForce RTX 3090 Ti', 'NVIDIA', 'mdrinnan15', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (192, 'GeForce MX330', 'NVIDIA', 'kfowleyo', 7);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (193, 'CMP 50HX', 'NVIDIA', 'espooner5', 5);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (194, 'RTX A3000 Mobile', 'NVIDIA', 'icosgreave1b', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (195, 'RTX A5000', 'NVIDIA', 'dliles1e', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (196, 'T400 4 GB', 'NVIDIA', 'cespinosad', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (197, 'Quadro T1200 Mobile', 'NVIDIA', 'dharbour1m', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (198, 'A100 PCIe 80 GB', 'NVIDIA', 'blarmour2b', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (199, 'Quadro T1200 Mobile', 'NVIDIA', 'obiskupiak1r', 23);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (200, 'CMP 70HX', 'NVIDIA', 'mludlama', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (201, 'GeForce GTX 1650 TU106', 'NVIDIA', 'aavramovitz9', 0);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (202, 'GeForce RTX 2080 SUPER Mobile', 'NVIDIA', 'mdrinnan15', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (203, 'GeForce RTX 2070 SUPER Mobile', 'NVIDIA', 'rfishleigh1u', 3);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (204, 'A100 PCIe 80 GB', 'NVIDIA', 'cmclaineb', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (205, 'GeForce RTX 2070 SUPER', 'NVIDIA', 'megdellh', 7);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (206, 'GeForce GTX 1650 TU106', 'NVIDIA', 'bheyburn2r', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (207, 'Quadro RTX 3000 Mobile', 'NVIDIA', 'afortounj', 35);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (208, 'GeForce RTX 3080 Ti', 'NVIDIA', 'dpiddletownf', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (209, 'Quadro P3200 Max-Q', 'NVIDIA', 'cmclaineb', 0);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (210, 'GeForce GT 1010', 'NVIDIA', 'emilligan3', 23);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (211, 'GeForce GTX 1060 6 GB GP104', 'NVIDIA', 'luppetth', 33);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (212, 'Quadro RTX 6000', 'NVIDIA', 'kpopworth2r', 27);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (213, 'GeForce GTX 1650 SUPER', 'NVIDIA', 'twyrill7', 23);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (214, 'GeForce RTX 2080 Max-Q', 'NVIDIA', 'mludlama', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (215, 'Quadro P2000 Mobile', 'NVIDIA', 'rgorey1e', 8);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (216, 'Quadro RTX 4000 Max-Q', 'NVIDIA', 'kberkowitz2o', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (217, 'Quadro RTX 3000 Mobile', 'NVIDIA', 'gcasemore1x', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (218, 'TITAN RTX', 'NVIDIA', 'wtorres29', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (219, 'RTX A500 Embedded', 'NVIDIA', 'rgorey1e', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (220, 'Tesla V100S PCIe 32 GB', 'NVIDIA', 'bcater1k', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (221, 'RTX A4500', 'NVIDIA', 'etripeang', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (222, 'GeForce RTX 3070 Mobile', 'NVIDIA', 'wstaterfield17', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (223, 'PG506-242', 'NVIDIA', 'bhallor1', 43);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (224, 'RTX A6000', 'NVIDIA', 'gnotleyc', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (225, 'GeForce RTX 2070 Mobile', 'NVIDIA', 'wgrebert2c', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (226, 'A100 SXM4 80 GB', 'NVIDIA', 'gbytheway6', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (227, 'GeForce GTX 1060 6 GB GP104', 'NVIDIA', 'aboleyn1j', 42);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (228, 'Quadro P520 Mobile', 'NVIDIA', 'byakutin2a', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (229, 'GeForce RTX 3060 Max-Q', 'NVIDIA', 'mdrinnan15', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (230, 'RTX A4500', 'NVIDIA', 'aleist8', 16);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (231, 'RTX A5000 Mobile', 'NVIDIA', 'jschroderd', 8);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (232, 'Tesla PG500-216', 'NVIDIA', 'dpiddletownf', 38);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (233, 'GeForce RTX 2070 Max-Q', 'NVIDIA', 'gbytheway6', 43);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (234, 'GeForce RTX 3050 4 GB', 'NVIDIA', 'jduffyn5', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (235, 'GeForce GTX 1660 Ti', 'NVIDIA', 'oheaslya', 42);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (236, 'GeForce RTX 2060 Mobile', 'NVIDIA', 'dliles1e', 15);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (237, 'RTX A1000 Embedded', 'NVIDIA', 'blarmour2b', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (238, 'GeForce RTX 2060 Mobile', 'NVIDIA', 'mludlama', 1);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (239, 'RTX A2000 Mobile', 'NVIDIA', 'icosgreave1b', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (240, 'GeForce RTX 4060', 'NVIDIA', 'aleist8', 27);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (241, 'GRID A100B', 'NVIDIA', 'ckytleyb', 31);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (242, 'GeForce RTX 3050 8 GB', 'NVIDIA', 'sreignard27', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (243, 'GeForce GT 1010 DDR4', 'NVIDIA', 'jduffyn5', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (244, 'GeForce RTX 2070 SUPER', 'NVIDIA', 'hellacottz', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (245, 'GeForce RTX 2070', 'NVIDIA', 'gcasemore1x', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (246, 'GeForce RTX 3060', 'NVIDIA', 'snyssenk', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (247, 'GeForce RTX 2060 Mobile', 'NVIDIA', 'fkeepin1f', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (248, 'RTX A3000 Mobile', 'NVIDIA', 'lgredden9', 23);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (249, 'GeForce RTX 2080 Max-Q', 'NVIDIA', 'wflattg', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (250, 'GeForce RTX 3070 Ti', 'NVIDIA', 'emacaindreish', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (251, 'GeForce GTX 1650 Mobile', 'NVIDIA', 'bdradey8', 14);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (252, 'T600', 'NVIDIA', 'wtorres29', 43);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (253, 'A10G', 'NVIDIA', 'bheyburn2r', 16);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (254, 'RTX A4500 Embedded', 'NVIDIA', 'dpiddletownf', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (255, 'GeForce RTX 2060 TU104', 'NVIDIA', 'wgrebert2c', 11);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (256, 'GeForce RTX 3060 Ti GA103', 'NVIDIA', 'ctomeoi', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (257, 'Quadro P5200 Mobile', 'NVIDIA', 'blarmour2b', 47);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (258, 'GeForce RTX 3070', 'NVIDIA', 'etripeang', 33);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (259, 'GeForce GTX 1660 SUPER', 'NVIDIA', 'jduffyn5', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (260, 'RTX A1000 Embedded', 'NVIDIA', 'sreignard27', 11);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (261, 'GeForce GTX 1060 8 GB GDDR5X', 'NVIDIA', 'ymcphail1c', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (262, 'Quadro RTX 3000 Mobile', 'NVIDIA', 'jduffyn5', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (263, 'RTX A2000 12 GB', 'NVIDIA', 'zstobie15', 37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (264, 'GeForce RTX 3070 Ti Mobile', 'NVIDIA', 'rgorey1e', 10);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (265, 'GRID RTX T10-2', 'NVIDIA', 'wflattg', 48);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (266, 'Tesla V100 DGXS 16 GB', 'NVIDIA', 'ctomeoi', 46);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (267, 'GeForce RTX 3080 Ti 20 GB', 'NVIDIA', 'cmclaineb', 0);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (268, 'Quadro RTX 6000 Passive', 'NVIDIA', 'emilligan3', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (269, 'RTX A4000', 'NVIDIA', 'gocurrine2h', 31);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (270, 'GeForce GTX 1660 Ti', 'NVIDIA', 'lwhittlesn', 33);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (271, 'RTX A4500', 'NVIDIA', 'npalleske1q', 35);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (272, 'GeForce RTX 2080 SUPER Mobile', 'NVIDIA', 'gocurrine2h', 13);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (273, 'GeForce RTX 2070 Max-Q', 'NVIDIA', 'rfishleigh1u', 37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (274, 'RTX A4500', 'NVIDIA', 'dliles1e', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (275, 'GRID RTX T10-4', 'NVIDIA', 'icosgreave1b', 42);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (276, 'P104-101', 'NVIDIA', 'ckytleyb', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (277, 'GeForce GTX 1650 SUPER', 'NVIDIA', 'aavramovitz9', 14);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (278, 'GeForce RTX 3080 Ti Mobile', 'NVIDIA', 'bsheridant', 47);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (279, 'GeForce RTX 3070 Max-Q', 'NVIDIA', 'emacaindreish', 12);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (280, 'RTX A4000 Mobile', 'NVIDIA', 'mkyllford2d', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (281, 'RTX A4500 Mobile', 'NVIDIA', 'wtorres29', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (282, 'Quadro P520 Mobile', 'NVIDIA', 'wmouat1d', 36);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (283, 'Quadro T1000 Max-Q', 'NVIDIA', 'dtestin26', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (284, 'GeForce RTX 3060 Ti', 'NVIDIA', 'lgredden9', 3);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (285, 'GeForce RTX 3090 Ti', 'NVIDIA', 'mfuke23', 42);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (286, 'GeForce RTX 3080 Ti Mobile', 'NVIDIA', 'adanielyf', 18);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (287, 'GRID RTX T10-16', 'NVIDIA', 'etripeang', 4);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (288, 'RTX A2000 Mobile', 'NVIDIA', 'bbeggn', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (289, 'Quadro RTX 5000', 'NVIDIA', 'wgrebert2c', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (290, 'P102-100', 'NVIDIA', 'espooner5', 37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (291, 'GRID A100A', 'NVIDIA', 'ttomane', 0);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (292, 'GeForce RTX 2070 SUPER', 'NVIDIA', 'moreilly0', 7);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (293, 'A100 SXM4 80 GB', 'NVIDIA', 'bheyburn2r', 8);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (294, 'Tesla V100 SXM2 16 GB', 'NVIDIA', 'bsheridant', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (295, 'RTX A4000', 'NVIDIA', 'mdrinnan15', 31);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (296, 'GeForce MX450 30.5W 8Gbps', 'NVIDIA', 'bdradey8', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (297, 'GeForce GTX 1050 Max-Q', 'NVIDIA', 'gferry22', 10);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (298, 'GeForce RTX 3080 Max-Q', 'NVIDIA', 'gbeyer18', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (299, 'GRID RTX T10-2', 'NVIDIA', 'cespinosad', 3);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid,  Price) values (300, 'Quadro RTX 3000 Max-Q', 'NVIDIA', 'rgorey1e', 6);
