/***************************

  Populate the downloads table

****************************/

insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (1, 'GeForce RTX 3080 Ti 20 GB', 'NVIDIA', 'dskae2', 11);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (2, 'Quadro P3200 Max-Q', 'NVIDIA', 'ctulk1c', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (3, 'GeForce RTX 2070 Mobile', 'NVIDIA', 'mpenbarthy13', 15);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (4, 'GeForce RTX 3060 Max-Q', 'NVIDIA', 'rpagen24', 18);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (5, 'GRID RTX T10-4', 'NVIDIA', 'mcrollaf', 13);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (6, 'Tesla V100 DGXS 32 GB', 'NVIDIA', 'dswannie10', 49);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (7, 'A30 PCIe', 'NVIDIA', 'bchatelo', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (8, 'Quadro T2000 Mobile', 'NVIDIA', 'ccaslakev', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (9, 'P102-100', 'NVIDIA', 'avolet1l', 12);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (10, 'Quadro T2000 Max-Q', 'NVIDIA', 'pkase26', 5);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (11, 'PG506-232', 'NVIDIA', 'aprettjohn2o', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (12, 'GeForce MX250', 'NVIDIA', 'dskae2', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (13, 'GeForce RTX 3060 Mobile', 'NVIDIA', 'wconnikie2c', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (14, 'RTX A2000 Mobile', 'NVIDIA', 'astennes1k', 41);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (15, 'T1000 8 GB', 'NVIDIA', 'aargente2n', 19);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (16, 'GeForce RTX 4090', 'NVIDIA', 'lfollowsl', 11);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (17, 'GeForce GTX 1060 6 GB GDDR5X', 'NVIDIA', 'ctulk1c', 35);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (18, 'GeForce MX230', 'NVIDIA', 'tgoing25', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (19, 'Tesla V100 FHHL', 'NVIDIA', 'gcrebott1m', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (20, 'GeForce RTX 3080 12 GB', 'NVIDIA', 'mrathmell1n', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (21, 'RTX A4500 Mobile', 'NVIDIA', 'pbertomier11', 13);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (22, 'T600 Mobile', 'NVIDIA', 'tbonnick1j', 22);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (23, 'CMP 30HX', 'NVIDIA', 'sherreros28', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (24, 'GeForce GTX 1650 Max-Q', 'NVIDIA', 'aenstone2r', 3);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (25, 'Quadro P4200 Mobile', 'NVIDIA', 'ptierney19', 1);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (26, 'Quadro GV100', 'NVIDIA', 'smarcussenw', 49);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (27, 'RTX A4500 Mobile', 'NVIDIA', 'nive1', 47);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (28, 'Quadro P520 Mobile', 'NVIDIA', 'elathwell2j', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (29, 'GeForce RTX 3060 Ti GA103', 'NVIDIA', 'ishilstoneb', 44);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (30, 'Tesla T4', 'NVIDIA', 'ldrohaner', 14);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (31, 'Quadro RTX 3000 Max-Q', 'NVIDIA', 'edellcasa1i', 26);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (32, 'GeForce RTX 3060 Max-Q', 'NVIDIA', 'mmonnelly1w', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (33, 'GeForce RTX 4080 Ti', 'NVIDIA', 'flyle2d', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (34, 'RTX A3000 Mobile', 'NVIDIA', 'tadamiakt', 14);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (35, 'Quadro P2000 Mobile', 'NVIDIA', 'ascourfield23', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (36, 'GeForce RTX 2080 Ti', 'NVIDIA', 'rpagen24', 33);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (37, 'GeForce RTX 2080 Ti', 'NVIDIA', 'flyle2d', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (38, 'GRID RTX T10-16', 'NVIDIA', 'mdeclerkk', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (39, 'GeForce RTX 2070 SUPER Mobile', 'NVIDIA', 'keffnert0', 40);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (40, 'GeForce GTX 1650 Max-Q', 'NVIDIA', 'mwedlake1q', 34);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (41, 'Quadro T1000 Mobile', 'NVIDIA', 'mmockett27', 32);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (42, 'RTX A5000', 'NVIDIA', 'krenzo1b', 31);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (43, 'RTX A4500', 'NVIDIA', 'aargente2n', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (44, 'P102-100', 'NVIDIA', 'ptierney19', 7);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (45, 'GeForce MX230', 'NVIDIA', 'avolet1l', 25);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (46, 'GeForce GTX 1060 6 GB GP104', 'NVIDIA', 'mmockett27', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (47, 'GeForce RTX 3060', 'NVIDIA', 'tbonnick1j', 21);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (48, 'GeForce GTX 1650 Ti Max-Q', 'NVIDIA', 'dswannie10', 3);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (49, 'RTX A6000', 'NVIDIA', 'clerohan1a', 43);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (50, 'Tesla V100 SXM2 32 GB', 'NVIDIA', 'lvest2p', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (51, 'GeForce RTX 2060', 'NVIDIA', 'aargente2n', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (52, 'Quadro T1000 Mobile', 'NVIDIA', 'rmcandrew1f', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (53, 'Quadro P3200 Max-Q', 'NVIDIA', 'adarley15', 33);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (54, 'Quadro T1000 Mobile GDDR6', 'NVIDIA', 'sstrevensq', 10);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (55, 'GeForce GTX 1660 SUPER', 'NVIDIA', 'hklimschak21', 46);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (56, 'P106M', 'NVIDIA', 'zmalebyg', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (57, 'Tesla PG503-216', 'NVIDIA', 'cimison12', 22);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (58, 'GeForce GTX 1650 GDDR6', 'NVIDIA', 'citter20', 47);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (59, 'GeForce RTX 2080', 'NVIDIA', 'rlindstrom9', 48);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (60, 'GeForce RTX 3080 Max-Q', 'NVIDIA', 'nive1', 18);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (61, 'GeForce RTX 2060 Mobile Refresh', 'NVIDIA', 'tsargant1e', 3);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (62, 'GeForce RTX 3070 Ti 16 GB', 'NVIDIA', 'crosenblatt1g', 47);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (63, 'RTX A1000 Embedded', 'NVIDIA', 'pkase26', 3);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (64, 'GeForce RTX 3090 Ti', 'NVIDIA', 'aloader17', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (65, 'Quadro T2000 Mobile', 'NVIDIA', 'aduthie2l', 13);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (66, 'T600', 'NVIDIA', 'rlindstrom9', 23);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (67, 'GeForce GTX 1050 3 GB', 'NVIDIA', 'ebortolotti2e', 30);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (68, 'CMP 170HX', 'NVIDIA', 'jlancashire2i', 27);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (69, 'GeForce RTX 2070 SUPER', 'NVIDIA', 'rmcandrew1f', 12);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (70, 'GeForce RTX 3070 Max-Q', 'NVIDIA', 'tbonnick1j', 50);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (71, 'Switch GPU 16nm', 'NVIDIA', 'sherreros28', 12);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (72, 'GeForce RTX 4060', 'NVIDIA', 'rcostelloe6', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (73, 'T400', 'NVIDIA', 'hsacco2a', 6);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (74, 'RTX A5000', 'NVIDIA', 'ctulk1c', 15);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (75, 'RTX A5000', 'NVIDIA', 'oheadey3', 27);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (76, 'CMP 40HX', 'NVIDIA', 'pkase26', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (77, 'A100 PCIe 80 GB', 'NVIDIA', 'flyle2d', 18);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (78, 'P104-101', 'NVIDIA', 'dcostelloe1z', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (79, 'TITAN V CEO Edition', 'NVIDIA', 'hsacco2a', 32);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (80, 'GeForce RTX 3070 Ti', 'NVIDIA', 'gbrabbanp', 45);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (81, 'T600 Mobile', 'NVIDIA', 'ttrobex', 37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (82, 'GeForce RTX 3080 Max-Q', 'NVIDIA', 'mwedlake1q', 28);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (83, 'Quadro RTX 3000 Mobile Refresh', 'NVIDIA', 'tbonnick1j', 20);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (84, 'GeForce RTX 2060 Mobile Refresh', 'NVIDIA', 'wconnikie2c', 39);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (85, 'GeForce GTX 1080 Ti 10 GB', 'NVIDIA', 'oheadey3', 42);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (86, 'GeForce RTX 2080 Mobile', 'NVIDIA', 'adowniej', 24);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (87, 'GeForce RTX 2060 Max-Q', 'NVIDIA', 'flyle2d', 29);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (88, 'Quadro P500 Mobile', 'NVIDIA', 'bimbrey5', 5);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (89, 'GeForce RTX 4090', 'NVIDIA', 'aprettjohn2o', 9);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (90, 'Quadro P500 Mobile', 'NVIDIA', 'aargente2n', 15);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (91, 'GeForce GTX 1070 GDDR5X', 'NVIDIA', 'folin1t', 2);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (92, 'GeForce GTX 1660 Ti', 'NVIDIA', 'rcostelloe6', 37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (93, 'Quadro P5200 Mobile', 'NVIDIA', 'tbonnick1j', 22);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (94, 'T1000 8 GB', 'NVIDIA', 'zmalebyg', 17);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (95, 'GeForce RTX 2080', 'NVIDIA', 'omussilli1p',37);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (96, 'Quadro T1000 Mobile GDDR6', 'NVIDIA', 'aavrahamyy', 14);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (97, 'Quadro P5200 Max-Q', 'NVIDIA', 'gbrabbanp', 15);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (98, 'GeForce GTX 1050 Ti Max-Q', 'NVIDIA', 'ependrid18', 36);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (99, 'GeForce GT 1030 GK107', 'NVIDIA', 'ldrohaner', 35);
insert into GPU_Listing_Archive (Listingid, GPU_model, GPU_brand, Customerid, Price) values (100, 'RTX A5000 Mobile', 'NVIDIA', 'elathwell2j', 43);
